pipeline {
    agent any

    environment {
        IMAGE_NAME = "azat279/mybuildimage"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build(IMAGE_NAME)
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_creds_id') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
    }
}
